# Generated by Django 3.2.7 on 2022-08-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.CharField(default='Hello World, this is my blog post', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='My blog post', max_length=255),
        ),
    ]
