# Generated by Django 3.2.7 on 2022-08-11 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("phonebook", "0004_auto_20220811_2216"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="auth.user"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
