# Generated by Django 3.2.7 on 2022-08-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0006_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
