# Generated by Django 3.2.7 on 2022-08-23 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0007_post_author_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='author_id',
        ),
    ]
