# Generated by Django 3.2.7 on 2022-06-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='highlighted',
            field=models.TextField(blank=True),
        ),
    ]
