# Generated by Django 3.2.7 on 2022-06-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonebookcontact',
            name='code',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
