# Generated by Django 3.2.7 on 2022-06-22 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0002_phonebookcontact_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonebookcontact',
            name='code',
        ),
    ]
